language: node_js
node_js:
  - '8'
  - '6'
before_install:
  - npm set progress=false
  - npm config ls
script: npm test
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
cache:
  directories:
  - node_modules